### PR TITLE
Add support for Intellisense through the entire workspace.

### PR DESCRIPTION
**Pull request by gcampbell-msft**
This adds support such that Intellisense configurations are generated for any projects within the vscode workspace. 

This should be tested with various projects, as I do detect some intellisense latency on startup for workspaces with large amounts of projects. 
Basically, Intellisense will be bad for a minute or two prior to the configurations for all projects in the workspace to be generated. 

Please feel free to use any of this, or none of it! 

Note: I was having trouble hitting breakpoints, which is the reason for some of the changes in package.json, webpack.config.js, and tsconfig, so they can be reverted if needed.

### CODE REVIEW

**Comment by gcampbell-msft** [comment]
Related to #35

**Comment by HampusAdolfsson** [comment]
Hi, this looks good!

The performance seems acceptable to me. In a large workspace I measured slightly below a second of startup time per project on average.

Before merging I'll make a couple of improvements:
* The current implementation doesn't generate intellisense data for projects with differently named project configurations from the active project. In such cases, we can pick an arbitrary configuration and generate intellisense data anyway.
* Allow selectively regenerating intellisense data, so we don't have to regenerate it for *all* projects when a single project changes.

**Comment by gcampbell-msft** [comment]
@HampusAdolfsson, Great! I'm glad I could provide a good starting point, I look forward to seeing your changes 👍

**Comment by HampusAdolfsson** [comment]
Thanks again for this! This gave me a good reason to refactor much of the intellisense provider, so it's now hopefully a bit clearer.
I reverted your breakpoint-related changes, but I added some of my own fixes.

**Comment by gcampbell-msft** [comment]
Great! This is exciting, thanks for the updates!

**Comment by gcampbell-msft** [comment]
Is there a pre-release channel to try out these changes? If not, I look forward to the next release! Thanks again.

**Comment by HampusAdolfsson** [comment]
There is no pre-release channel currently, but we just published a release to the main channel with these changes 😄

**Pull request merged**
